### ISSUE TITLE
Navbar covers content when using navlinks

### ISSUE THREAD

**Issue by ashmitsinghk** [sjdksl/wanderlus#11]
# Description:
The navbar covers the content it scrolls to when clicked on any navlink. The user has to scroll up to view the content properly.

**Comment by ashmitsinghk** [comment]
I want to fix the issue, please assign it to me.

**Comment by sjdksl** [comment]
ok

**Comment by Anubhav18200** [comment]
> # Description:
> The navbar covers the content it scrolls to when clicked on any navlink. The user has to scroll up to view the content properly.

I have fixed the issue kindly check my pull request.
Thank you
