### ISSUE TITLE
Text size on small devices

### ISSUE THREAD

**Issue by sjdksl** [sjdksl/wanderlus#13]
**Issue: Increase Text Size on Small Devices**

**Description:**
The current text size on the website is too small on small devices, making it challenging for users to read and interact with the content comfortably. To enhance the user experience, we need to increase the text size for small screens.

**Steps to Reproduce:**
1. Access the website on a small mobile device or emulator.
2. Observe the text size, including headings, paragraphs, and navigation menus.

**Expected Behavior:**
Text should be legible and easily readable on small screens without the need for users to zoom in or strain their eyes. The increased text size should provide a more user-friendly experience.

**Priority:** Medium

**Tasks:**
- Review the current typography settings and CSS styles.
- Determine an appropriate font size and line height for text elements on small screens.
- Ensure that headings, paragraphs, and other critical text elements are adequately sized for mobile users.
- Update the CSS styles to reflect the increased text size.
- Test the changes on various small devices to verify improved readability.
- Consider responsive design principles to maintain a harmonious layout while adjusting the text size.

**Additional Information:**
- This improvement is essential for improving the overall usability and accessibility of the website on mobile devices.
- Ensure that the changes are consistent with the website's design and branding guidelines.

**Comment by Ahnaf-codes** [comment]
@sjdksl i'd like to work on this please assign me

**Comment by sjdksl** [comment]
Ok
