### ISSUE TITLE
wrong content spelling

### ISSUE THREAD

**Issue by sjdksl** [sjdksl/wanderlus#2]
### Issue Description

There is a typo in the Usage heading of the README file. The word "conttent" should be corrected to "content" for accuracy and readability.

### Steps to Reproduce

- Navigate to the "Usage" section in the README file.
- Observe the typo in the context.

### Expected Behavior

The "conttent" have correct spelling and read as "content"

### Screenshots (if applicable)

[Insert screenshots here if they help illustrate the issue.]

**Comment by ashmitsinghk** [comment]
Would like to work on this issue, kindly assign.

**Comment by sjdksl** [comment]
ok sure

**Comment by sjdksl** [comment]
issue is fixed
