### ISSUE TITLE
Fork step should be added

### ISSUE THREAD

**Issue by sjdksl** [sjdksl/wanderlus#3]
### Issue Description

Currently, the "Installation" section lacks a step that instructs users to fork the repository. Forking is an essential step for contributing to the project or working on it locally. We should add a clear "Fork" step with instructions on how to fork the repository.

### Proposed Change

Add the following step to the "Installation" section of the README:

1. **Fork the Repository**: Click the "Fork" button at the top right of the [GitHub repository page](https://github.com/your-username/your-project) to create your own copy of the project. This is necessary if you plan to contribute to the project or work on it locally.

### Expected Behavior

The "Installation" section of the README should include a clear and concise step for users to fork the repository, enhancing the documentation and helping newcomers get started with the project.

### Screenshots (if applicable)

[Insert screenshots here if they help illustrate the proposed change.]

**Comment by aasthalovespasta** [comment]
Please assign me this issue
