### ISSUE TITLE
change wanderlus to wanderlust

### ISSUE THREAD

**Issue by sjdksl** [sjdksl/wanderlus#4]
### Issue Description

In the README file, there are instances of "wanderlus" that need to be corrected to "wanderlust" for consistency and accuracy. This change should be applied to all occurrences throughout the document.

### Proposed Change

Replace all instances of "wanderlus" with "wanderlust" in the README file.

### Expected Behavior

After this change is implemented, the README will use the correct spelling "wanderlust" consistently, improving readability and accuracy.

### Screenshots (if applicable)

[Insert screenshots here if they help illustrate the proposed change.]

**Comment by SagarKapoorin** [comment]
please assign me this issue

**Comment by sjdksl** [comment]
ok
